Traceback (most recent call last):
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/naudsluis/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot the Iris dataset using Plotly
g1 = px.scatter_3d(df,
                   x="sepal_width",
                   y="sepal_length",
                   z="petal_width",
                   color="species",
                   size="petal_length",
                   opacity=0.6,
                   size_max=30,
                   height=700)
g1
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m [38;5;66;03m# Plot the Iris dataset using Plotly[39;00m
[0;32m----> 2[0m g1 [38;5;241m=[39m [43mpx[49m[38;5;241;43m.[39;49m[43mscatter_3d[49m[43m([49m[43mdf[49m[43m,[49m
[1;32m      3[0m [43m                   [49m[43mx[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43msepal_width[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      4[0m [43m                   [49m[43my[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43msepal_length[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      5[0m [43m                   [49m[43mz[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpetal_width[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      6[0m [43m                   [49m[43mcolor[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mspecies[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      7[0m [43m                   [49m[43msize[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpetal_length[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      8[0m [43m                   [49m[43mopacity[49m[38;5;241;43m=[39;49m[38;5;241;43m0.6[39;49m[43m,[49m
[1;32m      9[0m [43m                   [49m[43msize_max[49m[38;5;241;43m=[39;49m[38;5;241;43m30[39;49m[43m,[49m
[1;32m     10[0m [43m                   [49m[43mheight[49m[38;5;241;43m=[39;49m[38;5;241;43m700[39;49m[43m)[49m
[1;32m     11[0m g1

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/plotly/express/_chart_types.py:776[0m, in [0;36mscatter_3d[0;34m(data_frame, x, y, z, color, symbol, size, text, hover_name, hover_data, custom_data, error_x, error_x_minus, error_y, error_y_minus, error_z, error_z_minus, animation_frame, animation_group, category_orders, labels, size_max, color_discrete_sequence, color_discrete_map, color_continuous_scale, range_color, color_continuous_midpoint, symbol_sequence, symbol_map, opacity, log_x, log_y, log_z, range_x, range_y, range_z, title, template, width, height)[0m
[1;32m    730[0m [38;5;28;01mdef[39;00m [38;5;21mscatter_3d[39m(
[1;32m    731[0m     data_frame[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    732[0m     x[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m    770[0m     height[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    771[0m ) [38;5;241m-[39m[38;5;241m>[39m go[38;5;241m.[39mFigure:
[1;32m    772[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    773[0m [38;5;124;03m    In a 3D scatter plot, each row of `data_frame` is represented by a[39;00m
[1;32m    774[0m [38;5;124;03m    symbol mark in 3D space.[39;00m
[1;32m    775[0m [38;5;124;03m    """[39;00m
[0;32m--> 776[0m     [38;5;28;01mreturn[39;00m [43mmake_figure[49m[43m([49m[43margs[49m[38;5;241;43m=[39;49m[38;5;28;43mlocals[39;49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mconstructor[49m[38;5;241;43m=[39;49m[43mgo[49m[38;5;241;43m.[39;49m[43mScatter3d[49m[43m)[49m

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/plotly/express/_core.py:1996[0m, in [0;36mmake_figure[0;34m(args, constructor, trace_patch, layout_patch)[0m
[1;32m   1993[0m layout_patch [38;5;241m=[39m layout_patch [38;5;129;01mor[39;00m {}
[1;32m   1994[0m apply_default_cascade(args)
[0;32m-> 1996[0m args [38;5;241m=[39m [43mbuild_dataframe[49m[43m([49m[43margs[49m[43m,[49m[43m [49m[43mconstructor[49m[43m)[49m
[1;32m   1997[0m [38;5;28;01mif[39;00m constructor [38;5;129;01min[39;00m [go[38;5;241m.[39mTreemap, go[38;5;241m.[39mSunburst, go[38;5;241m.[39mIcicle] [38;5;129;01mand[39;00m args[[38;5;124m"[39m[38;5;124mpath[39m[38;5;124m"[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1998[0m     args [38;5;241m=[39m process_dataframe_hierarchy(args)

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/plotly/express/_core.py:1409[0m, in [0;36mbuild_dataframe[0;34m(args, constructor)[0m
[1;32m   1406[0m     args[[38;5;124m"[39m[38;5;124mcolor[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m   1407[0m [38;5;66;03m# now that things have been prepped, we do the systematic rewriting of `args`[39;00m
[0;32m-> 1409[0m df_output, wide_id_vars [38;5;241m=[39m [43mprocess_args_into_dataframe[49m[43m([49m
[1;32m   1410[0m [43m    [49m[43margs[49m[43m,[49m[43m [49m[43mwide_mode[49m[43m,[49m[43m [49m[43mvar_name[49m[43m,[49m[43m [49m[43mvalue_name[49m
[1;32m   1411[0m [43m[49m[43m)[49m
[1;32m   1413[0m [38;5;66;03m# now that `df_output` exists and `args` contains only references, we complete[39;00m
[1;32m   1414[0m [38;5;66;03m# the special-case and wide-mode handling by further rewriting args and/or mutating[39;00m
[1;32m   1415[0m [38;5;66;03m# df_output[39;00m
[1;32m   1417[0m count_name [38;5;241m=[39m _escape_col_name(df_output, [38;5;124m"[39m[38;5;124mcount[39m[38;5;124m"[39m, [var_name, value_name])

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.11/site-packages/plotly/express/_core.py:1208[0m, in [0;36mprocess_args_into_dataframe[0;34m(args, wide_mode, var_name, value_name)[0m
[1;32m   1206[0m         [38;5;28;01mif[39;00m argument [38;5;241m==[39m [38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m:
[1;32m   1207[0m             err_msg [38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;124m To use the index, pass it in directly as `df.index`.[39m[38;5;124m"[39m
[0;32m-> 1208[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(err_msg)
[1;32m   1209[0m [38;5;28;01melif[39;00m length [38;5;129;01mand[39;00m [38;5;28mlen[39m(df_input[argument]) [38;5;241m!=[39m length:
[1;32m   1210[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1211[0m         [38;5;124m"[39m[38;5;124mAll arguments should have the same length. [39m[38;5;124m"[39m
[1;32m   1212[0m         [38;5;124m"[39m[38;5;124mThe length of column argument `df[[39m[38;5;132;01m%s[39;00m[38;5;124m]` is [39m[38;5;132;01m%d[39;00m[38;5;124m, whereas the [39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m   1219[0m         )
[1;32m   1220[0m     )

[0;31mValueError[0m: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class'] but received: sepal_width

